# Generated by Django 2.1.2 on 2019-04-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantradio',
            old_name='owners',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='first_test_variants',
            name='test',
        ),
        migrations.RemoveField(
            model_name='first_test_variants',
            name='variant',
        ),
        migrations.AddField(
            model_name='first_test_variants',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_test_variant', to='Diplom.QuestionRadio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='first_test_variants',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='first_test_variants',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='answer_of_TEST1', to='Diplom.Student'),
        ),
    ]
