# Generated by Django 2.1.2 on 2019-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='answers', to='Diplom.Test'),
        ),
    ]
