# Generated by Django 2.1.2 on 2019-04-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0002_auto_20190415_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seventh_test_variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('owner', models.ManyToManyField(blank=True, related_name='seventh_test_variant', to='Diplom.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seventh_test_variant', to='Diplom.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Third_test_variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('owner', models.ManyToManyField(blank=True, related_name='third_test_variant', to='Diplom.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_test_variant', to='Diplom.Test')),
            ],
        ),
    ]
