# Generated by Django 2.1.2 on 2019-04-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0002_auto_20190405_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TextAnswers', to='Diplom.Student'),
        ),
    ]
