# Generated by Django 2.1.2 on 2019-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0003_seventh_test_variants_third_test_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionradio',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
