# Generated by Django 2.1.2 on 2019-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0004_auto_20190415_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_test_variants',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
