# Generated by Django 2.1.2 on 2019-04-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0004_auto_20190405_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_test_variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=1)),
                ('test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Diplom.Test', verbose_name='questions')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='answer_of_TEST1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Diplom.First_test_variants'),
            preserve_default=False,
        ),
    ]
