# Generated by Django 2.1.2 on 2019-04-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0005_auto_20190405_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='answer_of_TEST1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Diplom.First_test_variants'),
        ),
    ]
