# Generated by Django 2.1.2 on 2019-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0006_auto_20190405_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
