# Generated by Django 2.1.2 on 2019-04-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0007_test_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_test_variants',
            name='test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_test_variants', to='Diplom.Test'),
        ),
        migrations.AlterField(
            model_name='questionradio',
            name='test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Diplom.Test'),
        ),
    ]
