# Generated by Django 2.1.2 on 2019-04-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0008_auto_20190406_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTest6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test6Answers', to='Diplom.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTest8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test8Answers', to='Diplom.Student')),
            ],
        ),
        migrations.CreateModel(
            name='NumberQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.Test', verbose_name='questions')),
            ],
        ),
    ]
