# Generated by Django 2.1.2 on 2019-04-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0009_answertest6_answertest8_numberquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_questions', to='Diplom.Test'),
        ),
    ]
