# Generated by Django 2.1.2 on 2019-04-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0010_auto_20190406_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='answer_of_TEST1',
        ),
        migrations.AddField(
            model_name='first_test_variants',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_test_answer', to='Diplom.Student'),
            preserve_default=False,
        ),
    ]
