# Generated by Django 2.1.2 on 2019-04-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0012_auto_20190406_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
